version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: batam_dev
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server

#  app:
#    build:
#      context: .
#      dockerfile: app.Dockerfile
#    command: bash -c "bundle exec puma -C config/puma.rb"
#    volumes:
#      - .:/app
#    depends_on:
#      - 'redis'
#      - 'db'
#    environment:
#      - REDIS_URL=redis://redis:6379/0
#      - RAILS_SERVE_STATIC_FILES=true
#      - RAILS_ENV=production
#    env_file:
#      - '.env'
  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
#    depends_on:
#      - app
    ports:
      - 80:80

#  sidekiq:
#    depends_on:
#      - 'redis'
#    build: .
#    command: sidekiq -C config/sidekiq.yml.erb
#    volumes:
#      - '.:/app'
#    env_file:
#      - '.env'
#    environment:
#      - REDIS_URL=redis://redis:6379/0