---
verbose: false
concurrency: 10
pidfile: ./tmp/pids/sidekiq.pid
logfile: ./log/sidekiq.log
queues:
  - default
  - low
production:
  concurrency: 25
staging:
  concurrency: 15

:schedule:
#  clean_data:
#    cron: '0 0 * * *'   # 00:00 every day
#    class: CleanData
#  update_tomorrow_trip:
#    cron: '5 0 * * *'   # 00:05 every day
#    class: UpdateTomorrowTrip
  write_data_log:
    every: '5m'
    class: WriteSeatTransLog
  end_trip:
    every: '5m'
    class: EndTrip


